# Generated by Django 4.1.3 on 2022-11-25 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auctions",
            "0007_alter_bidding_bidding_price_alter_listing_bidding_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist_id",
            field=models.ManyToManyField(
                blank=True,
                related_name="listing_watchlist_id",
                through="auctions.Watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
