# Generated by Django 4.1.3 on 2022-11-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_listing_watchlist_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.TextField(
                choices=[
                    ("1", "Apparel and accessories"),
                    ("2", "Auto and parts"),
                    ("3", "Book, music and video"),
                    ("4", "Computer, technology and eletronics"),
                    ("5", "Furniture"),
                    ("6", "Health, personal care and beauty"),
                    ("7", "Office"),
                    ("8", "Toys and hobby"),
                    ("9", "Other"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="listing_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist_listing_id",
                to="auctions.listing",
            ),
        ),
    ]
