# Generated by Django 4.1.3 on 2022-11-28 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_listing_category_alter_watchlist_listing_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="listing_image"),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="creator_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist_creator_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
